# Generated by Django 4.2.8 on 2023-12-15 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("factory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="factory", name="user",),
        migrations.AddField(
            model_name="factory",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
